[package]
name = "voyager-record"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.0"

[[bin]]
name = "voyager-record"
path = "src/main.rs"
